version: 0.2
env:
  variables:
      NODE_ENV: $STAGE

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      # - . env/.env.$STAGE
      - ls -ltr
      - python -m pip install --upgrade aws-sam-cli
      - sam --version
  pre_build:
    commands:
      - echo $STAGE
  build:
    commands:
      - ls -ltr
      - sam deploy -t packaged.yaml --stack-name $STACK_NAME --s3-bucket $ARTIFACT_BUCKET --region $REGION --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --no-fail-on-empty-changeset --parameter-overrides "ParameterKey=Environment,ParameterValue=${ENVIRONMENT}" "ParameterKey=ResourcePrefix,ParameterValue=${PREFIX}" "ParameterKey=Region,ParameterValue=${REGION}" "ParameterKey=CloudFrontDomain,ParameterValue=${CLOUDFRONT_DOMAIN}" "ParameterKey=CallRecordBucket,ParameterValue=${CALL_RECORD_BUCKET}" "ParameterKey=RDSHost,ParameterValue=${RDS_HOST}" "ParameterKey=RDSPort,ParameterValue=${RDS_PORT}" "ParameterKey=RDSUsername,ParameterValue=${RDS_USERNAME}" "ParameterKey=RDSPassword,ParameterValue=${RDS_PASSWORD}" "ParameterKey=RDSSchemaName,ParameterValue=${RDS_SCHEMA_NAME}" || true