# testing
AWSTemplateFormatVersion: '2010-09-09'
Description: Simple S3 Bucket Creation

Globals:
  Function:
    Timeout: 480
Parameters:
  Region:
    Type: String
    Default: ""
  ResourcePrefix:
    Type: String
    Default: ""
  Environment:
    Type: String
    Default: ""

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Environment}-${ResourcePrefix}-simple-s3-bucket-123456"

Outputs:
  S3BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref MyS3Bucket
